module.exports = {
  sidebar: [
    {
      type: "autogenerated",
      dirName: "categories"
    }
  ],
  serverSidebar: [
    "server-api",
    "server-options"
  ],
  clientSidebar: [
    "client-api",
    "client-options"
  ],
  changelogSidebar: [
    {
      type: "autogenerated",
      dirName: "changelog"
    }
  ],
  tutorialSidebar: [
    {
      type: "autogenerated",
      dirName: "tutorial"
    }
  ],
};
